### ISSUE TITLE
Spam errors

### ISSUE THREAD

**Issue by DarkFort** [devblook/miniannouncer#6]
I do not understand why 
Errors https://hastebin.com/share/qoyuziyola.ruby
Config https://hastebin.com/share/acuzehiwaw.bash

**Comment by jonakls** [comment]
Hi @DarkFort 

Thanks for your input, I will be checking it out.

**Comment by jonakls** [comment]
Hi @DarkFort 

Reviewing your report, the failure is not due to a bug in the plugin. It is a bug in line 34 of your configuration, which by putting "!" you are breaking the formatting

* Incorrect format
```yaml
- "[MESSAGE]<white>Введите перед сообщением символ "!", например: !Привет всем"
```
* Correct format
```yaml
- "[MESSAGE]<white>Введите перед сообщением символ \"!\", например: !Привет всем"
```

Please validate this and I look forward to hearing from you!
