### ISSUE TITLE
High CPU Load over time

### ISSUE THREAD

**Issue by fmohican** [devblook/miniannouncer#9]
Hello,
After i install the plugin, the server start to use more and more cpu till crash.

https://spark.lucko.me/JtiKE7YQ5z

After i remove the plugin everything work smooth.

**Comment by jonakls** [comment]
Hi @fmohican 

I show you some tests in more complicated conditions against what you show me and where it is reflected that my pl does not have a high consumption, moreover, what you show reflects the same way that my pl does not have any kind of consumption.

This first profiler is without any player
https://spark.lucko.me/NyrvCTWFfL

In this one, I find myself, in which I am without any anomaly.
https://spark.lucko.me/6DtPj5miDZ

**Comment by fmohican** [comment]
Hi @jonakls, thanks for quick anwser.

Yes, that was the problem, the empty server without anyone on it, is increasing cpu usage overtime.
Unfortunately, after I discovered where the problem was, I deleted both the plugin and the configuration folder...

is it possible that a configuration error is causing this problem? should I try to add the plugin back and configure it again?

**Comment by fmohican** [comment]
I reinstall the plugin and redo configuration, everything is fine. sorry for bother.
